In [6]:
#!/usr/bin/env python
import numpy as np

def labelize(x):
    if x > 0.5:
        return 1
    return 0

def sigmoid(x):
    return x
    #return 1.0 / (1 + np.exp(-x))

#train data set 
feature_size = 3
sample_num = 10
train_features = np.random.randint(0,10,size=(sample_num,feature_size)) 
#train_labels = map(labelize, np.random.rand(sample_num,1)) 
weights = [1,2,3]
train_labels = sigmoid(np.sum(weights * train_features,1))
print train_features
print train_labels


#setup hyper-parameters 
batch_size = 5
epoch_num = 10
learning_rate = 0.01
weights = np.zeros(feature_size)

#start traning
for epoch in range(epoch_num):
    c = list(zip(train_features,train_labels))
    np.random.shuffle (c)
    train_features,train_labels = zip(*c)
    
    for i in range(0, len(train_features), batch_size):
        sigmoid_predict = sigmoid(np.sum(weights * train_features[i : i + batch_size],1))
        
        sample_size = len(train_labels[i : i + batch_size])
        batch_grad = train_features[i : i + batch_size] * \
        (sigmoid_predict - train_labels[i : i + batch_size]).reshape(sample_size, 1)
        batch_grad = np.mean(batch_grad, 0 )
    
        weights -= learning_rate * batch_grad
    
    #predict
    print("Current weights is: {}".format(weights))
    #print 'epoch {}'.format(epoch)
    #print 'target {}'.format(train_labels)
    #sigmoid_predict = sigmoid(np.sum(weights * train_features,1))
    #print 'predict {}'.format(sigmoid_predict)
    

[[4 8 2]
 [0 8 3]
 [4 7 1]
 [1 0 9]
 [0 8 2]
 [3 6 6]
 [8 2 2]
 [2 8 8]
 [1 6 2]
 [8 4 3]]
[26 25 21 28 22 33 18 42 19 25]
Current weights is: [ 1.01788   2.105496  1.706172]
Current weights is: [ 1.17584558  2.3220134   2.12146911]
Current weights is: [ 1.1886141   2.34884385  2.33874764]
Current weights is: [ 1.16547084  2.2921774   2.47092234]
Current weights is: [ 1.13234718  2.22687939  2.56167101]
Current weights is: [ 1.11145409  2.18680969  2.64531946]
Current weights is: [ 1.08479154  2.13829009  2.70258472]
Current weights is: [ 1.07386793  2.12028445  2.76299037]
Current weights is: [ 1.05510454  2.09013506  2.80188154]
Current weights is: [ 1.04934706  2.081064    2.84311719]
